### ISSUE TITLE
Why is there no forward direction process in BDL.py ?

### ISSUE THREAD

**Issue by nakashima-kodai** [liyunsheng13/BDL#1] opened 2019-05-06 17:01 UTC
In your paper, using the bidirectional lerning, the image translation model and the segmentation adaptation model can be learned alternatively. But, I think there is not forward direction process in BDL.py. Please teach me the reason. Thank you in advance.

**Comment by liyunsheng13** [comment] 2019-05-06 17:05
I think you mean the image translation model. I put it in the folder named cyclegan. But I only upload the different files compared to the official CycleGAN model.

**Comment by nakashima-kodai** [comment] 2019-05-06 17:08
What I want to say is whether it is acceptable not to learn image translation model and segmentation model at the same time.

**Comment by liyunsheng13** [comment] 2019-05-06 17:23
Yes, you can

**Comment by nakashima-kodai** [comment] 2019-05-06 17:24
How can I do that ?

**Comment by liyunsheng13** [comment] 2019-05-06 17:26
It seems that I don’t fully understand you question. You can train the BDL.py to learn segmentation model and train cyclegan to learn the image translation model. Is that clear?

**Comment by nakashima-kodai** [comment] 2019-05-06 17:38
Yes, I know that. In other words, do you mean that you did not learn CycleGAN and DeepLab in one iteration?

**Comment by nakashima-kodai** [comment] 2019-05-06 17:54
Yes, I know that. To sum up, does it mean that it should be executed like train_cyclegan.py (the result is uploaded)-> BDL.py-> SSL.py-> BDL.py?

**Comment by liyunsheng13** [comment] 2019-05-06 17:59
Yes, I also upload the model to train SSL.py.

**Comment by nakashima-kodai** [comment] 2019-05-06 18:01
Oh, ok. Thank you very much.

**Comment by liyunsheng13** [comment] 2019-05-06 18:11
No problem

**Comment by DLwbm123** [comment] 2019-05-11 11:45
Hi! I did't get the idea clearly either. There is really no training code for cycleGAN in BDL.py. And cycleGAN need to be trained first so that it didn't get feedback from segmentation model to update. So, could you explain more accurately and clearly about the ''Bidirectional training''  process? In my mind,  the cycleGAN should be learned with the segmentation model in an alternative way in BDL.py instead of training it separately before training segmentation model. Thank you!

**Comment by liyunsheng13** [comment] 2019-05-11 21:28
First of all, it is not an end-to-end system. I train CycleGAN and Segmentation model separately. Actually, if you combine them together, you will have the memory issue and also the unstable training process. What I did here is to train a CycleGAN first (code is in the fold of CycleGAN) and then use the translated images to train the segmentation model with BDL.py. In order to build feedback between the two models to implement the bidirectional learning, you can use the segmentation model as a perception loss to help train the CycleGAN again. The whole code for CycleGAN still needs sometime to be cleaned but currently I upload the most important part of it (I upload the different files compared to the official CycleGAN work). I also upload the translated images given by CycleGAN, you can easily reproduce the results in the paper by using those images with BDL.py. Maybe the name BDL.py confuses you a little bit, I will rename it with 'segmentation.py' or other names. Hope my explanation helps you

**Comment by DLwbm123** [comment] 2019-05-12 02:28
> First of all, it is not an end-to-end system. I train CycleGAN and Segmentation model separately. Actually, if you combine them together, you will have the memory issue and also the unstable training process. What I did here is to train a CycleGAN first (code is in the fold of CycleGAN) and then use the translated images to train the segmentation model with BDL.py. In order to build feedback between the two models to implement the bidirectional learning, you can use the segmentation model as a perception loss to help train the CycleGAN again. The whole code for CycleGAN still needs sometime to be cleaned but currently I upload the most important part of it (I upload the different files compared to the official CycleGAN work). I also upload the translated images given by CycleGAN, you can easily reproduce the results in the paper by using those images with BDL.py. Maybe the name BDL.py confuses you a little bit, I will rename it with 'segmentation.py' or other names. Hope my explanation helps you

I get more clear about the idea and I will read the codes more carefully. Thanks for you kindly explanation and patience!

**Comment by changliu816** [comment] 2019-05-16 19:37
Hi!  For the translated GTA5 as Cityscape dataset by CycleGAN you uploaded, it is the result of first-time trained CycleGAN or the second time trained CycleGAN with perception loss ? Thank you !

**Comment by liyunsheng13** [comment] 2019-05-16 21:14
It is the translated images given by the second CycleGAN with perception loss.

**Comment by ghost** [comment] 2019-06-02 14:05
Hi,Can you tell me the value of finesize and loadsize when testing? @liyunsheng13

**Comment by liyunsheng13** [comment] 2019-06-02 20:26
The loadsize is 1024 and the finesize is 452 when I did experiments. The gpu I use in Microsoft has 16G memory. So if the gpu you used only has 12G memory, I suggest you to decrease the finesize to 400 or some other values, otherwise it will have the out of memory issue. Although I think decreasing the finesize might has a bad influence on the performance, the influence might be very tiny.

**Comment by PJ1yang** [comment] 2019-06-03 00:56
The transferred image you provided is 1024x568. Is this because you get the 452X452 image and resize it to 1024X568? @liyunsheng13

**Comment by ghost** [comment] 2019-06-03 03:06
The transferred image you provided is 1024x568. Is this because you get the 452X452 image and resize it to 1024X568?so 1024X568 is the input size of segmentation model and dont need crop to 321 or some other values?@liyunsheng13

**Comment by liyunsheng13** [comment] 2019-06-03 03:11
No, I resize the image to 1024*568 and crop to 452*452 to train cyclegan. I suggest you to read the code or the paper more carefully.

**Comment by ghost** [comment] 2019-06-03 04:55
ok,thank you very much

**Comment by octpath** [comment] 2019-06-18 22:01
> What I did here is to train a CycleGAN first (code is in the fold of CycleGAN) and then use the translated images to train the segmentation model with BDL.py. In order to build feedback between the two models to implement the bidirectional learning, you can use the segmentation model as a perception loss to help train the CycleGAN again.

Hi. I have some questions about initial weights of CycleGAN.
When I train CycleGAN with perception loss for the first time, are the initial weights of the generators and the discriminators transfered from vanilla (without perception loss) CycleGAN?
Also, are init weights of 2nd CycleGAN w/ perception loss transfered from 1st one?
Thank you.

**Comment by liyunsheng13** [comment] 2019-07-19 17:13
For training CycleGAN, you can just randomly initialize it for both the 1st and the 2nd time.

**Closed as completed** 2021-01-14 08:12 UTC
