### ISSUE TITLE
Dataset download failed

### ISSUE THREAD

**Issue by QingL0218** [liyunsheng13/BDL#5] opened 2019-06-04 01:46 UTC
Hi, yunsheng, I can't open the GTA5 as CityScapes url on drive.google, could you please give other urls  for example on Baiduyun? THX

**Comment by liyunsheng13** [comment] 2019-06-04 01:49
Is it because the Chinese government blocks google? I'm sorry I don't use Baiduyun. If you cannot download the data, we might need to think another way to let you access the data.

**Comment by QingL0218** [comment] 2019-06-04 09:52
ok, waiting for you

**Comment by liyunsheng13** [comment] 2019-06-04 18:05
Could you use VPN to download the data? I originally want to send it via email but I think the size of data is too big. I also try to create an account for Baiduyun but it requires a Chinese mobile phone number which I don't have.

**Comment by ghost** [comment] 2019-06-07 12:32
hi，When I train cyclegan, GA can easily turn the sky in GTAV into a tree. Do you know what the problem is?thank you @liyunsheng13

**Comment by liyunsheng13** [comment] 2019-06-07 18:18
You are right. This problem is hard to be solved. I think it is caused by the difference of the spatial layout between GTA5 and Cityscapes dataset. For GTA5, there is not a lot of trees in the sky part but the Cityscapes is different. When CycleGAN is trained, it realize that spatial layout difference and tries to convert it from source domain to the target domain. If you train CycleGAN with datasets that have larger domain gap, you can find this phenomenon more obvious. Right now, there is not a way to solve this problem. I suggest you to make the identity loss or the reconstruction perception loss more important. They might help. Btw, as this question is different from the dataset download problem, I create a new issue. And you can get the same answer there.

**Comment by chep1126** [comment] 2019-07-17 09:19
Hi,did you download this dataset successfully? I can't open the url on drive.google,either.

**Comment by chep1126** [comment] 2019-07-19 01:16
Hi,I solved the problem，and I've transferred the data to BaiduYun.

**Comment by QingL0218** [comment] 2019-07-19 07:14
I couldn't solve this problem,Could you give me the download link?THX

**Comment by chep1126** [comment] 2019-07-19 08:43
> I couldn't solve this problem,Could you give me the download link?THX

链接：https://pan.baidu.com/s/1eGGFWruh9e2FhVFX_0vmQA 
提取码：nzro

**Comment by jn-z** [comment] 2019-08-25 22:33
@chep1126 Hi, can you continue to share your Baidu Cloud Link? I found that the shared file had expired. Thank you！

**Comment by chep1126** [comment] 2019-08-26 01:42
> @chep1126 Hi, can you continue to share your Baidu Cloud Link? I found that the shared file had expired. Thank you！

链接: https://pan.baidu.com/s/1jlR1o7GtnxiQpvbpimMZAw 
提取码: ku7f

**Comment by JiangXiaobai00** [comment] 2019-12-21 12:37
Has anybody  downloaded the gta5 raw dataset sucessfully ?I want to train the cyclegan,but  failed to get the dataset .

**Closed as completed** 2021-06-17 18:58 UTC
